## Dependencies Stage
FROM docker.io/node:16 AS mycelium-international-client-base

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --non-interactive


## App Stage
FROM mycelium-international-client-base AS build-base

WORKDIR /app

COPY . .

RUN yarn run build


## App Stage
FROM docker.io/node:16 AS mycelium-international-client

WORKDIR /app

# Copy build
COPY --from=build-base --chown=node:node /app/ .

USER node

CMD [ "yarn", "run", "server" ]