## Dependencies Stage
FROM docker.io/node:16 AS mycelium-international-client

WORKDIR /app

# Expose directory to the outside
VOLUME /app

CMD bash -c "yarn install --non-interactive && yarn run dev"