@startuml sequence1

participant "Administrator/Employee" as user
participant "Frontend Server\nRequest" as fe
participant "API Server\nRequest" as api
participant "Database Session" as db
participant "International\nIntegration\nAPI Request" as integ

user -> fe : GET /search
activate fe
user <-- fe : Webpage contents
deactivate fe
user -> api : GET /search?q={text}&category={category}&...
activate api
api -> api : Build query
api -> db : Send query
activate db
api <-- db : List of products
deactivate db
api -> integ : GET /search?q={text}&category={category}&...
activate integ
api <-- integ : List of products
deactivate integ
api -> api : Join list of products
user <-- api : List of products
deactivate api

@enduml