@startuml sequence1

participant "Administrator/Employee" as user
participant "Frontend Server\nRequest" as fe
participant "API Server\nRequest" as api
participant "Database Session" as db

user -> fe : GET /product/1
activate fe
user <-- fe : Webpage contents
deactivate fe
user -> api : GET /product/1
activate api
api -> db : Get product with id
activate db
api <-- db : Product data
deactivate db
api -> db : Get product comments
activate db
api <-- db : List of product comments
deactivate db
api -> api : Build JSON object
user <-- api : Send JSON object
deactivate api
user -> user : Write comment
user -> api : POST /product/1/comment
activate api
api -> db : Create comment on specified product
activate db
api <-- db : Confirm
deactivate db
user <-- api : Confirm
deactivate api

@enduml