kind: pipeline
type: docker

name: Pipeline

platform:
  os: linux
  arch: amd64

steps:
- name: Unit Tests
  image: gradle:7.5.1-jdk17
  commands:
    - cd api
    - ./gradlew test
  when:
    event:
      - push
      - pull_request

- name: SonarQube Back
  image: gradle:7.5.1-jdk17
  commands:
    - cd api
    - gradle sonar
  when:
    event:
      - push
      - pull_request

- name: SonarQube Front
  image: node:16.18.1
  commands:
    - npm install -g sonarqube-scanner
    - sonar-scanner

- name: Email
  image: drillster/drone-email
  settings:
    host: smtp.gmail.com
    username: lmenendez@unis.edu.gt
    password: slqmkgjuxxvhmasa
    from: lmenendez@unis.edu.gt
    subject: La etapa $DRONE_STAGE_NAME ha fallado.
    recipients: 
      - luisenriquem15@gmail.com
  when:
    status:
    - failure
