name: mycelium-local-dev

services:
  nginx-proxy:
    image: nginx
    ports:
      - "6062:80/tcp"
    volumes:
      - ./default.conf:/etc/nginx/templates/default.conf.template:z,ro
    networks:
      - mycelium-local
    depends_on:
      - api
      - client

  api:
    image: localhost/mycelium-local_api:prod
    expose:
      - "8080"
    build:
      context: api
      dockerfile: Dockerfile.prod
    networks:
      - mycelium-local
    depends_on:
      - db

  client:
    image: localhost/mycelium-local_client:prod
    expose:
      - "3000"
    build:
      context: client
      dockerfile: Dockerfile.prod
    networks:
      - mycelium-local

  db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    expose:
      - "1521"
    restart: unless-stopped
    environment:
      ORACLE_PWD: "12345"
    volumes:
      - oracledb:/opt/oracle/oradata:z,rw
    networks:
      mycelium-local:
        aliases:
          - myceliumdb

volumes:
  oracledb:

networks:
  mycelium-local:
    driver: bridge