name: mycelium-local-dev

services:
  nginx-proxy:
    image: nginx
    ports:
      - "6062:80/tcp"
    volumes:
      - ./default.conf:/etc/nginx/templates/default.conf.template:z,ro
    networks:
      mycelium-local:
      mycelium-global:
        aliases:
          - mycelium-local
    depends_on:
      - api
      - client

  api:
    image: localhost/mycelium-local_api:dev
    expose:
      - "8080"
    volumes:
      - ./api:/app:z,rw
      - gradle:/var/lib/gradle:z,rw
    build:
      context: api
      dockerfile: Dockerfile.dev
    networks:
      - mycelium-local
      - mycelium-global
    depends_on:
      - db

  client:
    image: localhost/mycelium-local_client:dev
    expose:
      - "3000"
    volumes:
      - ./client:/app:z,rw
    build:
      context: client
      dockerfile: Dockerfile.dev
    networks:
      - mycelium-local
      - mycelium-global

  db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    ports:
      - 2521:1521
    restart: unless-stopped
    environment:
      ORACLE_PWD: "12345"
    volumes:
      - oracledb:/opt/oracle/oradata:z,rw
    networks:
      mycelium-local:
        aliases:
          - myceliumdb

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - mycelium-local
    environment:
      - SONARQUBE_JDBC_USERNAME=Sonar
      - SONARQUBE_JDBC_PASSWORD=12345
      - SONARQUBE_JDBC_URL=jdbc:oracle:thin:@db:2521/XEPDB1
    depends_on:
      - db
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions

volumes:
  oracledb:
  gradle:
  jenkins_home:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:

networks:
  mycelium-local:
    driver: bridge
  mycelium-global:
    external: true