scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080

- job_name: 'jenkins'
  metrics_path: '/prometheus'
  static_configs:
  - targets: 
    - jenkins:8080