create table "users" (
  "id" number(10) generated by default as identity(start with 1) not null,
  "name" varchar2(50),
  "lastname" varchar2(50),
  "email" varchar2(200),
  "password" varchar2(50),
  "roleId" number(10),
  primary key ("id")
);
create table "userRole" (
  "id" number(10) generated by default as identity(start with 1) not null,
  "name" varchar2(50),
  primary key ("id")
);
create table "integrations" (
  "id" number(10) generated by default as identity(start with 1) not null,
  "name" varchar2(50),
  "request" varchar2(200),
  "user" varchar2(50),
  "password" varchar2(50),
  primary key ("id")
);
create table "pictures" (
  "id" number(10) generated by default as identity(start with 1) not null,
  "url" varchar2(200),
  "productId" number(10),
  primary key ("id")
);
create table "products" (
  "id" number(10) generated by default as identity(start with 1) not null,
  "name" varchar2(50),
  "desc" varchar2(200),
  "categorieId" number(10),
  "brand" varchar2(50),
  "weight" number(10),
  "quantity" number(10),
  "price" number(10),
  primary key ("id")
);
create table "categories" (
  "id" number(10) generated by default as identity(start with 1) not null,
  "name" varchar2(50),
  primary key ("id")
);
create table "technical" (
  "id" number(10) generated by default as identity(start with 1) not null,
  "type" varchar2(50),
  "value" varchar2(50),
  "productId" number(10),
  primary key ("id")
);
create table "jsonLog" (
  "id" number(10) generated by default as identity(start with 1) not null,
  "userId" number(10),
  "when" timestamp,
  "operation" number,
  "archiveName" varchar2(50),
  "success" number(10),
  "error" number(10),
  primary key ("id")
);
create table "errorLog" (
  "id" number(10) generated by default as identity(start with 1) not null,
  "message" varchar2(200),
  "jsonLogId" number(10),
  primary key ("id")
);
create table "carts" (
  "id" number(10) generated by default as identity(start with 1) not null,
  "productId" number(10),
  "quantity" number(10),
  "userId" number(10),
  primary key ("id")
);
create table "orderProducts" (
  "id" number(10) generated by default as identity(start with 1) not null,
  "orderId" number(10),
  "productId" number(10),
  "quantity" number(10),
  "statusId" number(10),
  "tracking" varchar2(50),
  "time" number(10),
  "integOrderId" number(10),
  "created" timestamp,
  "updated" timestamp,
  primary key ("id")
);
create table "status" (
  "id" number(10) generated by default as identity(start with 1) not null,
  "name" varchar2(50),
  primary key ("id")
);
create table "orderMessages" (
  "orderId" number(10),
  "statusId" number(10),
  "message" varchar2(200),
  primary key ("orderId", "statusId")
);
create table "ratings" (
  "id" number(10) generated by default as identity(start with 1) not null,
  "userId" number(10),
  "productId" number(10),
  "rating" number(10),
  primary key ("id")
);
create table "comments" (
  "id" number(10) generated by default as identity(start with 1) not null,
  "userId" number(10),
  "productId" number(10),
  "commentId" number(10),
  "message" varchar2(200),
  "created" timestamp,
  "updated" timestamp,
  primary key ("id")
);
create table "orders" (
  "id" number(10) generated by default as identity(start with 1) not null,
  "userId" number(10),
  "direction" varchar2(200),
  "state" varchar2(50),
  "city" varchar2(50),
  "zip" number(10),
  "phone" number(10),
  "since" timestamp,
  "till" timestamp,
  primary key ("id")
);
create table "integOrderProducts" (
  "id" number(10) generated by default as identity(start with 1) not null,
  "orderId" number(10),
  "productId" number(10),
  "quantity" number(10),
  "statusIntegId" number(10),
  "statusLocalId" number(10),
  "trackingInteg" varchar2(50),
  "trackingLocal" varchar2(50),
  "timeInteg" number(10),
  "timeLocal" number(10),
  "integrationId" number(10),
  "created" timestamp,
  "updated" timestamp,
  primary key ("id")
);
create table "cartInteg" (
  "id" number(10) generated by default as identity(start with 1) not null,
  "productId" number(10),
  "quantity" number(10),
  "userId" number(10),
  primary key ("id")
);
alter table "users"
  add foreign key ("roleId")
  references "userRole" ("id");
alter table "pictures"
  add foreign key ("productId")
  references "products" ("id");
alter table "products"
  add foreign key ("categorieId")
  references "categories" ("id");
alter table "technical"
  add foreign key ("productId")
  references "products" ("id");
alter table "jsonLog"
  add foreign key ("userId")
  references "users" ("id");
alter table "errorLog"
  add foreign key ("jsonLogId")
  references "jsonLog" ("id");
alter table "carts"
  add foreign key ("userId")
  references "users" ("id");
alter table "carts"
  add foreign key ("productId")
  references "products" ("id");
alter table "orderProducts"
  add foreign key ("productId")
  references "products" ("id");
alter table "orderProducts"
  add foreign key ("statusId")
  references "status" ("id");
alter table "orderMessages"
  add foreign key ("statusId")
  references "status" ("id");
alter table "orderMessages"
  add foreign key ("orderId")
  references "orderProducts" ("id");
alter table "ratings"
  add foreign key ("userId")
  references "users" ("id");
alter table "ratings"
  add foreign key ("productId")
  references "products" ("id");
alter table "comments"
  add foreign key ("userId")
  references "users" ("id");
alter table "comments"
  add foreign key ("productId")
  references "products" ("id");
alter table "comments"
  add foreign key ("commentId")
  references "comments" ("id");
alter table "orderProducts"
  add foreign key ("orderId")
  references "orders" ("id");
alter table "orders"
  add foreign key ("userId")
  references "users" ("id");
alter table "integOrderProducts"
  add foreign key ("integrationId")
  references "integrations" ("id");
alter table "integOrderProducts"
  add foreign key ("statusIntegId")
  references "status" ("id");
alter table "integOrderProducts"
  add foreign key ("statusLocalId")
  references "status" ("id");
alter table "integOrderProducts"
  add foreign key ("orderId")
  references "orders" ("id");
alter table "cartInteg"
  add foreign key ("userId")
  references "users" ("id");