@startuml sequence1

participant "User" as user
participant "Frontend Server\nRequest" as fe
participant "API Server\nRequest" as api
participant "Database Session" as db

user -> fe : GET /admin/product
activate fe
user <-- fe : Webpage contents
deactivate fe
user -> api : GET /product/export
activate api
api -> db : Get list of products
activate db
api <-- db : Return list of products
deactivate db
user <-- api : Serialize to JSON and send
deactivate api

@enduml