@startuml sequence1

actor "Usuario" as user
entity "Frontend Server\nRequest" as fe
entity "API Server\nRequest" as api
database "Database Session" as db

user -> fe : GET /admin/product
activate fe
fe -> user : Webpage contents
deactivate fe
user -> api : POST /product/export with JSON file of products
activate api
api -> api : validate
api -> db : INSERT INTO products(...) VALUES (...)
activate db
db -> api : Confirm
deactivate db
api -> user : Confirm
deactivate api
user -> fe : Reload page (GET /admin/product)
activate fe
fe -> user : Webpage contents
deactivate fe

@enduml