@startuml sequence1

participant "Administrator/Employee" as user
participant "Frontend Server\nRequest" as fe
participant "API Server\nRequest" as api
participant "Database Session" as db

user -> fe : GET /reports
activate fe
user <-- fe : Webpage contents
deactivate fe
user -> api : GET /reports/available
activate api
user <-- api : Send available report generators
deactivate api
user -> api : GET /reports/generate?document=sales\n&fields=name,price,type,user
activate api
api -> api : Build query
api -> db : Send query
activate db
api <-- db : Return document references
deactivate db
user <-- api : Serialize to JSON and send
deactivate api

@enduml