@startuml sequence1

participant "Administrator/Employee" as user
participant "Frontend Server\nRequest" as fe
participant "API Server\nRequest" as api
participant "Database Session" as db

user -> fe : GET {route}
activate fe
user <-- fe : Webpage contents
deactivate fe

user -> api : GET /interface?route={route}
activate api
api -> db : Get texts for the specified route
activate db
api <-- db : List of texts for the specified route
deactivate db
user <-- api : List of texts for the specified route
deactivate api
user -> user : Replace placeholders\nwith the texts given

@enduml