FROM docker.io/alpine/git:latest AS entr-cloner

WORKDIR /app

RUN git clone --depth=1 https://github.com/eradman/entr.git --branch 5.3 .

FROM docker.io/alpine:3.17.2 AS gcc-base

RUN set -ex && \
    apk add --no-cache gcc make musl-dev

FROM gcc-base AS entr-builder

COPY --from=entr-cloner /app /app

WORKDIR /app

ENV DESTDIR=/app/build

RUN make -f ./Makefile.linux install

FROM docker.io/openjdk:17-alpine AS runner

COPY --from=entr-builder /app/build/usr/local/bin/entr /usr/local/bin/entr

VOLUME /app

EXPOSE 8080

ENTRYPOINT [ "/app/dev-entrypoint.sh" ]

